[package]
name = "rust_database-connections"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
mongodb = "3.1.0"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }
